# Generated by Django 5.1.7 on 2025-11-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_product', 'Может публиковать и снимать товар с публикации')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
