# Generated by Django 5.1.7 on 2025-10-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_tag_alter_category_options_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='catalog.product', verbose_name='Товар')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Инструкции по уходу')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country_origin', models.CharField(blank=True, max_length=50, verbose_name='Страна производства')),
                ('production_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год производства')),
                ('warranty_period', models.CharField(blank=True, max_length=50, verbose_name='Гарантийный срок')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Штрих-код')),
            ],
            options={
                'verbose_name': 'Детальная информация о товаре',
                'verbose_name_plural': 'Детальная информация о товарах',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
    ]
