# Generated by Django 5.1.7 on 2025-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productdetail_product_catalog_pro_created_eee82f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
