# Generated by Django 5.1.7 on 2025-11-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='collections/%Y/%m/%d/', verbose_name='Изображение коллекции'),
        ),
    ]
