# Generated by Django 5.1.7 on 2025-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-time_create'], name='homepage_co_time_cr_79e7cb_idx'),
        ),
    ]
