# Generated by Django 5.1.7 on 2025-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Опубликовано'),
        ),
    ]
