# Generated by Django 5.1.7 on 2025-10-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_collection_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-time_create'], 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
